Update main.py | small bug fix, where copying analog clock from default to AOD will cause error
I was getting this error when trying to copy the analog widget, 
please check on your side if this issue raises.

>Traceback (most recent call last):
  File "Mi-Create\src\main.py", line 1077, in copySelectedWatchfaceWi    
if widgetType["widget"].getProperty("analog_hour_image") != "":
       ~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'