Update project.py | small fix for can't open fprj if data source is not integer
fix for this error:-
ValueError: invalid literal for int() with base 10: '0A11'

when the unpacked unpacks the watch face sometimes the value of 'hour high' is '0A11' instead of '1000911'